apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pizza
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: local/frontend
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2UNENCRYPTEDSUPPORT
          value: 'true'
        - name: Service__Ingredients__Http__Host
          value: 'ingredients'
        - name: Service__Ingredients__Http__Port
          value: '80'
        - name: Service__Ingredients__Http__Protocol
          value: 'http'
        - name: Service__Orders__Http__Host
          value: 'orders'
        - name: Service__Orders__Http__Port
          value: '80'
        - name: Service__Orders__Http__Protocol
          value: 'http'

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pizza
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
