apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredients
  namespace: pizza
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingredients
  template:
    metadata:
      labels:
        app: ingredients
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: ingredients
        image: local/ingredients
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2UNENCRYPTEDSUPPORT
          value: 'true'
        - name: Jaeger__ServiceName
          value: 'ingredients'
        - name: Jaeger__Host
          value: 'jaeger-agent'
        - name: Jaeger__Port
          value: '6831'

---

apiVersion: v1
kind: Service
metadata:
  name: ingredients
  namespace: pizza
spec:
  selector:
    app: ingredients
  ports:
  - port: 80
